server:
  address: 127.0.0.1
  port: 8082

spring:
  application:
    name: authorization-resource

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://spring-oauth-server:8080

logging:
  level:
    org.springframework.security: trace
