server:
  address: 127.0.0.1
  port: 8081

spring:
  application:
    name: authorization-client

  security:
    oauth2:
      client:
        provider:
          oauth-server:
            # 认证 url
            issuer-uri: http://spring-oauth-server:8080
            # 授权 url
            authentication-uri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/authorize
            # token
            token-uri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/token
        registration:
          messageing-client-oidc:
            provider: oauth-server
            client-name: messageing-client
            # 客户端 ID
            client-id: messageing-client
            # 客户端 secret
            # 明文
            client-secret: 123456
            # 客户端认证方式
            client-authentication-method: client_secret_basic
            # 授权方式
            authoriaztion-grant-type: authorization_code
            redirect-uri: http://spring-oauth-client:8081/login/oauth2/code/messageing-client-oidc
            scope:
              - profile
              - openid

logging:
  level:
    org.springframework.security: trace
